---
functional: 
 -Пользователь должен иметь возможность искать товары по ключевому слову или категории
 -Пользователь должен иметь возможность фильтровать товары
 -Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
 -Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
 -Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
 -Сайт должен быть безопасным и защищать данные пользователя
 -Сайт должен иметь мобильную версию
 -Сайт нужно протестировать на совместимость с последними версиями браузеров
 -Важно, чтобы сайт мог обрабатывать большое количество трафика
 -Сайт должен быть доступен на различных устройствах

implicit:
 -Сайт должен работать круглосуточно 24\7
 -Цена не может быть отрицательной 
 -Должна быть возможность сброса фильтра
 -Должна быть функция "поделиться" собранной корзиной
 -Пользователь должен иметь возможность оформить заказ
 -Сайт должен работать на старых версиях браузера
 -Нужна возможность добавлять нужное количество товара в корзину
 -Должна быть возожность удалять нужное количество товара из корзины 
 -Поиск товара по ключевому слову и категории должен находить товары со всего каталога товаров
